spring:
  profiles:
    active: local

  application:
    name: cbj-ai-code-mother-backen

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: root
# ???????
server:
  port: 8123
  servlet:
#    ?????(????????/api)
    context-path: /api


# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
#      ?????
      packages-to-scan: com.yupi.cbjaicodemother.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

